using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Client.Message;
using Content.Trauma.Shared.ArcForging.ArcFurnaceConsole;

namespace Content.Trauma.Client.ArcForging.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class ArcFurnaceConsoleWindow : DefaultWindow
    {
        public ArcFurnaceConsoleWindow()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);
        }

        private ArcFurnaceConsoleBoundUserInterfaceState? _lastUpdate;

        public void Populate(ArcFurnaceConsoleBoundUserInterfaceState state)
        {
            _lastUpdate = state;
            // Build Console UI
            if (state.FurnaceConnected)
            {
                ArcFurnaceControl.Visible = true;
                ArcFurnaceMissing.Visible = false;
            }
            else
            {
                ArcFurnaceControl.Visible = false;
                ArcFurnaceMissing.Visible = true;
            }

            if (state.CraneConnected)
            {
                CraneMissing.Visible = false;
                CranePresent.Visible = true;
            }
            else
            {
                CraneMissing.Visible = true;
                CranePresent.Visible = false;
            }
        }
    }
}
